### ISSUE TITLE
Error in executing lua vim/_meta.lua: 324: Invalid option type 'nil' for 'filetype', should be string

### ISSUE THREAD

**Issue by ram02z** [Julian/lean.nvim#178]
Reproduction steps:
1. open a  standalone `.lean` file directly
2. Error shows on screen

Also, the filetype doesn't default to lean3 for whatever reason. Even when there is a `leanpkg.toml` file, the filetype stays at `lean`.

leanpkg.toml:
``` toml
[package]
name = "week2"
version = "0.1"
lean_version = "leanprover-community/lean:3.33.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "c2fde7017938c7c31d01cf14083774def7e0e018"}
```

Lean config: 
```lua
require("lean").setup{
  abbreviations = { builtin = true },
  lsp3 = { on_attach = on_attach },
  lsp = { enable = false },
  ft = { default = "lean3" },
  mappings = true,
}
```

Before the following commit, standalone `.lean` files wouldn't show this error.

Commit: 3aa953df9e5f18a61a3aeee0ca271973ceb1cde2

Nvim v0.6.0-dev
